[Icon Theme]
Name=ketsa

Directories=apps/64,places/64,places/16,mimetypes/128


Inherits=breeze,elementary,gnome,hicolor


[apps/64]
Size=64
Context=Applications
MinSize=16
MaxSize=512
Type=Scalable

[places/64]
Size=64
Context=Places
MinSize=16
MaxSize=512
Type=Scalable


[places/16]
Size=16
Context=Places
MinSize=8
MaxSize=512
Type=Scalable

[mimetypes/128]
Size=128
Context=mimetypes
MinSize=16
MaxSize=512
Type=Scalable


