 [Icon Theme]
Name=ketsa
Comment=oranchelo-icons is a set of flat icons some with long shadow, designed by adolfo silerio (zayronxio). originally based on superflat-remix, however, each day are more icons.
Directories=apps/64,places/64,
Inherits=gnome,Macos-sierra-CT

[apps/64]
Size=64
Context=Applications
MinSize=16
MaxSize=512
Type=Scalable

[places/64]
Size=64
Context=Places
MinSize=16
MaxSize=512
Type=Scalable
